[package]
name = "pluglib"
version = "0.1.0"
edition = "2021"

[dependencies]
btleplug = "0.11.6"
enum_dispatch = "0.3.13"
thiserror = "2.0.6"
tokio = "1.42.0"
tokio-stream = "0.1.17"
uuid = "1.11.0"

[dev-dependencies]
tokio = { version = "1.42.0", features = ["rt", "macros", "rt-multi-thread"] }
